name: Create Artifact
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  UploadArtifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create artifact folder
        run: mkdir -p artifacr

      - name: Add Text File
        run: echo hello > artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: artifact/world.txt
  
  DownloadArtifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: my-artifact
          
      - name: Display structure of downloaded files
        run: ls -R

