name: Runner Setup Demo
on: [push, workflow_dispatch]

permissions:
  id-token: write
  contents: read

jobs:
  Run-On-Push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: TerraformSession

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.2

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: '3.4.1'

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${{ secrets.S3_BUCKET }}" -backend-config="dynamodb_table=${{ secrets.DYNAMODB_TABLE }}"
      
      - name: Terraform Plan
        run: terraform plan -var='private_subnets=${{ secrets.PRIVATE_SUBNETS }}' -var='public_subnets=${{ secrets.PUBLIC_SUBNETS }}' -var='vpc_id=${{ secrets.VPC_ID }}' -var='role_arn=${{ secrets.AWS_ROLE }}'  --out tfplan
      
      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      - name: Set k8s context
        run: aws eks --region us-east-1 update-kubeconfig --name actions-runner-demo

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.23.6'
      
      - name: CoreDns Patch
        run: |
          kubectl patch deployment coredns -n kube-system --type=json -p='[{"op": "remove", "path": "/spec/template/metadata/annotations", "value": "eks.amazonaws.com/compute-type"}]'
          kubectl rollout restart -n kube-system deployment coredns
      
      - name: Cert Manager Install
        run: |
          helm repo add jetstack https://charts.jetstack.io
          helm repo update
          helm upgrade --install --wait --create-namespace --namespace cert-manager cert-manager jetstack/cert-manager --version v1.10.0 --set installCRDs=true --set webhook.securePort=10260

      - name: Actions Controller Install
        run: |
          helm repo add actions-runner-controller https://actions-runner-controller.github.io/actions-runner-controller
          helm upgrade --install --namespace actions-runner-system --create-namespace\
            --set=authSecret.create=true\
            --set=authSecret.github_token="${{ secrets.PAT_TOKEN }}"\
            --wait actions-runner-controller actions-runner-controller/actions-runner-controller
          kubectl --namespace actions-runner-system get all
